export const stateslist = [
    {key:'FC', value:'Abuja'},
    {key:'AB', value: 'Abia'},
    {key:'AD', value: 'Adamawa'},
    {key:'AK', value: 'Akwa Ibom'},
    {key:'AN', value: 'Anambra'},
    {key:'BA', value: 'Bauchi'},
    {key:'BY', value: 'Bayelsa'},
    {key:'BE', value: 'Benue'},
    {key:'BO', value: 'Borno'},
    {key:'CR', value: 'Cross River'},
    {key:'DE', value: 'Delta'},
    {key:'EB', value: 'Ebonyi'},
    {key:'ED', value: 'Edo'},
    {key:'EK', value: 'Ekiti'},
    {key:'EN', value: 'Enugu'},
    {key:'GO', value: 'Gombe'},
    {key:'IM', value: 'Imo'},
    {key:'JI', value: 'Jigawa'},
    {key:'KD', value: 'Kaduna'},
    {key:'KN', value: 'Kano'},
    {key:'KT', value: 'Katsina'},
    {key:'KE', value: 'Kebbi'},
    {key:'KO', value: 'Kogi'},
    {key:'KW', value: 'Kwara'},
    {key:'LA', value: 'Lagos'},
    {key:'NA', value: 'Nassarawa'},
    {key:'NI', value: 'Niger'},
    {key:'OG', value: 'Ogun'},
    {key:'ON', value: 'Ondo'},
    {key:'OS', value: 'Osun'},
    {key:'OY', value: 'Oyo'},
    {key:'PL', value: 'Plateau'},
    {key:'RI', value: 'Rivers'},
    {key:'SO', value: 'Sokoto'},
    {key:'TA', value: 'Taraba'},
    {key:'YO', value: 'Yobe'},
    {key:'ZA', value: 'Zamfara'},
]