import {
  SimpleLineIcons,
  MaterialCommunityIcons,
  FontAwesome6,
  MaterialIcons,
  Entypo,
  Ionicons,
} from "@expo/vector-icons";

export const demand = [
    {
        clientName: "AD Ola Agro Ent",
        address:"Lagos Ibadan Express Way",
        product:"Soya Bean",
        unit: 120,
        price:850000,
        date:"31/03/2025",

    },
    {
        clientName: "AD Ola Agro Ent",
        address:"Lagos Ibadan Express Way",
        product:"Soya Bean",
        unit: 120,
        price:850000,
        date:"31/03/2025",

    },
    {
        clientName: "AD Ola Agro Ent",
        address:"Lagos Ibadan Express Way",
        product:"Soya Bean",
        unit: 120,
        price:850000,
        date:"31/03/2025",

    },
    {
        clientName: "AD Ola Agro Ent",
        address:"Lagos Ibadan Express Way",
        product:"Soya Bean",
        unit: 120,
        price:850000,
        date:"31/03/2025",

    },
    {
        clientName: "AD Ola Agro Ent",
        address:"Lagos Ibadan Express Way",
        product:"Soya Bean",
        unit: 120,
        price:850000,
        date:"31/03/2025",

    },
]

export const quickAccess = [
  {
    title: "Add Farmer",
    icon: (
      <MaterialCommunityIcons name="account-group" size={34} color="#fff" />
    ),
    path: "/agent/onboardfarmer",
  },
  {
    title: "Request",
    icon: <FontAwesome6 name="clipboard-question" size={34} color="#fff" />,
    path: "/agent/request",
  },
  {
    title: "Farm Audit",
    icon: (
      <MaterialCommunityIcons name="archive-lock-open" size={34} color="#fff" />
    ),
    path: "/agent/farmAudit",
  },
  {
    title: "Aggregation",
    icon: <Entypo name="500px-with-circle" size={34} color="#fff" />,
    path: "/agent",
  },
  {
    title: "Market Price",
    icon: <FontAwesome6 name="sack-dollar" size={34} color="#fff" />,
    path: "/agent",
  },
  {
    title: "Support",
    icon: <FontAwesome6 name="handshake" size={34} color="#fff" />,
    path: "/agent",
  },
  {
    title: "Input Dist.",
    icon: (
      <MaterialCommunityIcons
        name="email-open-multiple"
        size={34}
        color="#fff"
      />
    ),
    path: "/agent",
  },
  {
    title: "Reports",
    icon: <Entypo name="open-book" size={34} color="#fff" />,
    path: "/agent",
  },
  {
    title: "Settings",
    icon: <Ionicons name="settings" size={34} color="#fff" />,
    path: "/agent",
  },
];

export const farmers = [
  {
    id: "1",
    name: "Idris Ahmed",
    gender: "Male",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Katsina",
    address: "5 Doguwa Street, Daura",
    community: "Daura",
    identification: "BVN",
    idNumber: "5655456377",
    farmSize: "5",
    crop: "Rice",
    season: "Rainfed",
    farmAddress: "Dada Area Daura ",
    bank: "EcoBank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "2",
    name: "Aisha Ibrahim",
    gender: "Female",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Kokoyo",
    identification: "NIN",
    idNumber: "QQ456377",
    farmSize: "3",
    crop: "Sorghum",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "3",
    name: "Gloria Mark",
    gender: "Female",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Kanam",
    identification: "NIN",
    idNumber: "TT456377",
    farmSize: "2",
    crop: "Sorghum",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "4",
    name: "Aliyu Abubakar",
    gender: "Male",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Kanam",
    identification: "NIN",
    idNumber: "TT456377",
    farmSize: "0.5",
    crop: "Sorghum",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "5",
    name: "Sadiya Umar",
    gender: "Female",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Kanam",
    identification: "NIN",
    idNumber: "UG456377",
    farmSize: "4",
    crop: "Tomatoes",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "6",
    name: "Musa Mai Shanu",
    gender: "Male",
    phoneNumber: "09088734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Kanam",
    identification: "BVN",
    idNumber: "5644352288",
    farmSize: "0.5",
    crop: "Sorghum",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "1234567890",
  },
  {
    id: "7",
    name: "Yakubu Dauda",
    gender: "Male",
    phoneNumber: "07065734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "20 Kangiwa Street, Zaria",
    community: "Sabon Garin",
    identification: "NIN",
    idNumber: "KK456377",
    farmSize: "2",
    crop: "Rice",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "0004567890",
  },
  {
    id: "8",
    name: "Shamsuddeen Aliyu",
    gender: "Male",
    phoneNumber: "09033734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "17 Alhaji Street, Zaria",
    community: "Sabon Gari",
    identification: "NIN",
    idNumber: "WQ456377",
    farmSize: "6",
    crop: "Tomatoes",
    season: "Dry Season",
    farmAddress: "Sabon Garin Zaria ",
    bank: "Access Bank Plc",
    accountNumber: "2124567890",
  },
  {
    id: "9",
    name: "Emmanuel James",
    gender: "Male",
    phoneNumber: "08032734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Kaduna",
    address: "10 Hajiya Street, Zaria",
    community: "Zaria",
    identification: "NIN",
    idNumber: "SX456377",
    farmSize: "0.5",
    crop: "Cabbages",
    season: "Dry Season",
    farmAddress: "Shika Zaria ",
    bank: "Union Bank Plc",
    accountNumber: "4534567890",
  },
  {
    id: "10",
    name: "Esther Bayero",
    gender: "Female",
    phoneNumber: "07058734524",
    email: "email@test.com",
    Nationality: "Nigeria",
    stateofOrigin: "Bauchi",
    address: "20 Baffajo Road",
    community: "Yelwa",
    identification: "BVN",
    idNumber: "205556377",
    farmSize: "2",
    crop: "Maize",
    season: "Dry Season",
    farmAddress: "KM 32 Gombe Road ",
    bank: "Access Bank Plc",
    accountNumber: "3234567890",
  },
];

export const trades = [
  {
    id: "1",
    name: "Seedlings Distribution",
    date: "07/4/2025",
    status: "In-Progress",
    
  },
  {
    id: "2",
    name: "Suya Beans Order",
    date: "28/3/2025",
    status: "In-Progress",
  },
  {
    id: "3",
    name: "Fertilizer Distribution",
    date: "25/3/2025",
    status: "Completed",
  },
  { id: "4", name: "Maize Order", date: "22/3/2025", status: "Completed" },
  { id: "5", name: "Maize Order", date: "22/3/2025", status: "Completed" },
  {
    id: "6",
    name: "Fertilizer Distribution",
    date: "25/3/2025",
    status: "Failed",
  },
  {
    id: "7",
    name: "Fertilizer Distribution",
    date: "25/3/2025",
    status: "Completed",
  },
  {
    id: "8",
    name: "Fertilizer Distribution",
    date: "25/3/2025",
    status: "Failed",
  },
  {
    id: "9",
    name: "Fertilizer Distribution",
    date: "25/3/2025",
    status: "Completed",
  },
];

